      - name: 安装 Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # 使用国内镜像下载命令行工具
          wget https://mirrors.aliyun.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android
          echo "ANDROID_HOME=$HOME/android" >> $GITHUB_ENV
          echo "PATH=$HOME/android/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
          # 阿里云sdk镜像
          yes | sdkmanager --sdk_root=$HOME/android --no_https "platforms;android-34" "build-tools;34.0.0" "ndk;26.2.11394342"
        env:
          REPO_OS_OVERRIDE: "linux"
      - name: 安装 Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # 使用国内镜像下载命令行工具
          wget https://mirrors.aliyun.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android
          echo "ANDROID_HOME=$HOME/android" >> $GITHUB_ENV
          echo "PATH=$HOME/android/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
          # 阿里云sdk镜像
          yes | sdkmanager --sdk_root=$HOME/android --no_https "platforms;android-34" "build-tools;34.0.0" "ndk;26.2.11394342"
        env:
          REPO_OS_OVERRIDE: "linux"
